{% set name = "python-iso639" %}
{% set version = "2024.4.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 97e63b5603e085c6a56a12a95740010e75d9134e0aab767e0978b53fd8824f13

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=65.3.0
    - wheel
    - pip
  run:
    - python >=3.8

test:
  imports:
    - iso639
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Look-up utilities for ISO 639 language codes and names
  home: https://github.com/jacksonllee/iso639
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
