{% set name = "python-iso639" %}
{% set version = "2024.4.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 97e63b5603e085c6a56a12a95740010e75d9134e0aab767e0978b53fd8824f13

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - setuptools >=65.3.0
    - wheel
    - pip
  run:
    - python

test:
  imports:
    - iso639
  requires:
    - pip
    - pytest
  source_files:
    - tests
  commands:
    - pip check
    # the additional parameters in the section tool.pytest.ini_options
    # in pyproject.toml for the are not actually used by the tests
    # 
    # skip test_version_number_match_with_changelog because it uses
    # the file CHANGELOG.md which is not included in the archive
    - pytest -v tests -k "not test_version_number_match_with_changelog"

about:
  home: https://github.com/jacksonllee/iso639
  license: Apache-2.0
  license_file: LICENSE.txt
  license_family: Apache
  summary: Look-up utilities for ISO 639 language codes and names
  description: |
    python-iso639 is a Python package for ISO 639 language codes,
    names, and other associated information.
  dev_url: https://github.com/jacksonllee/iso639
  doc_url: https://github.com/jacksonllee/iso639/blob/main/README.md

extra:
  recipe-maintainers:
    - jan-janssen
